remote_theme: zendesk/jekyll-theme-zendesk-garden@main
sidebar:
  - index
  - tuwhana
  - news
  - label: people
    children: 
      - researchers
      - students
      - advisoryboard
  - label: outputs
    children: 
      - publications
      - datasets
      - software
      - cves
  - vacancies
  - publications
